schema = 1

[release]
version = "1.0"
base_distribution = "opensuse-leap"
base_version = "16.1"
stage = "beta"
iteration = 1
codename = "Delos"
codename_id = "delos"
image_name = "LyraOS-Server"
architecture = "x86_64"
